### ISSUE TITLE
How to Start en el Readme

### ISSUE THREAD

**Issue by ZuraGuerra** [nfchero/webapp#1]
Vic y yo andamos intentando correr el proyecto with no success. ¿Podrían agregar instrucciones para correrlo? ¿Qué hay que instalar y así, qué versiones? ¿Y qué onda con la base de datos? -A Python00b

**Comment by ZuraGuerra** [comment]
@CoffiDev Si nos echaras una mano también, sería genial.

**Comment by miguelriego** [comment]
Hey! Ok, haré un mini walkthrough y lo pongo en slack ahorita
